"""
ReACT agent specifications for the time-series pipeline.

Each agent spec defines a deterministic Thought/Action/Observation contract
with explicit input/output schemas, validation rules, decision trees, and
error-handling paths.  This makes agent behaviour predictable and auditable
regardless of the underlying LLM or framework (Autogen / LangChain).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# AGENT_REACT_SPECS – structured ReACT definitions
#
# Each entry is a multi-line string that describes:
#   - Role & objective
#   - Input contract (what the agent expects)
#   - Output contract (what the agent produces)
#   - Decision tree (deterministic branching logic)
#   - Validation rules (pre-conditions that must hold)
#   - Error handling (what to do when pre-conditions fail)
#   - Thought/Action/Observation template
# ---------------------------------------------------------------------------

AGENT_REACT_SPECS: dict[str, str] = {
    "human_input_agent": (
        "ROLE: Input collector — gathers ticker and date range from the user.\n"
        "OBJECTIVE: Obtain a valid (ticker, start_date, end_date) triple.\n"
        "---\n"
        "INPUT_CONTRACT:\n"
        "  - ticker: str (non-empty, uppercase-alphanumeric, 1-10 chars)\n"
        "  - start_date: str (any supported date format — ISO, US, EU, relative, quarter)\n"
        "  - end_date: str (same formats as start_date)\n"
        "---\n"
        "VALIDATION_RULES:\n"
        "  1. ticker must match ^[A-Za-z0-9.]{1,10}$\n"
        "  2. start_date must parse via parse_date_str()\n"
        "  3. end_date must parse via parse_date_str()\n"
        "  4. start_date <= end_date (chronological order)\n"
        "  5. date range must not exceed 10 years (3652 days)\n"
        "  6. dates must be between 1900-01-01 and 2100-12-31\n"
        "---\n"
        "DECISION_TREE:\n"
        "  IF ticker is empty or invalid:\n"
        "    -> Action: prompt user for valid ticker\n"
        "    -> Repeat until valid or user cancels\n"
        "  IF start_date fails parse_date_str():\n"
        "    -> Action: show error with supported formats, re-prompt\n"
        "  IF end_date fails parse_date_str():\n"
        "    -> Action: show error with supported formats, re-prompt\n"
        "  IF start_date > end_date:\n"
        "    -> Action: swap dates automatically with warning\n"
        "  IF range exceeds 10 years:\n"
        "    -> Action: clamp end_date to start_date + 10 years with warning\n"
        "  ELSE:\n"
        "    -> Action: normalise both dates to YYYY-MM-DD, build PipelineRequest\n"
        "---\n"
        "ERROR_HANDLING:\n"
        "  - Empty input: re-prompt with example (e.g. 'AAPL', '2024-01-15')\n"
        "  - Unparseable date: list supported formats, show the failing input\n"
        "  - Non-interactive mode: raise ValueError with descriptive message\n"
        "---\n"
        "REACT_TEMPLATE:\n"
        "  Thought: collect required request context from user.\n"
        "  Action: ask for ticker and date range.\n"
        "  Observation: validated input available as PipelineRequest."
    ),
    "market_data_agent": (
        "ROLE: Market data retriever — fetches historical prices from all configured sources.\n"
        "OBJECTIVE: Return a list of DataSourceResult (one per source) with raw OHLC data.\n"
        "---\n"
        "INPUT_CONTRACT:\n"
        "  - request: PipelineRequest (ticker, start_date: date, end_date: date)\n"
        "  - sources: list[str] = ['bloomberg', 'reuters', 'yahoo']\n"
        "  - yahoo_mode: str = 'live' | 'stub'\n"
        "---\n"
        "OUTPUT_CONTRACT:\n"
        "  - results: list[DataSourceResult]\n"
        "  - Each result has: source, data (DataFrame with columns: date, ticker, close, source),\n"
        "    metadata (dict with: row_count, date_range, fetch_timestamp)\n"
        "---\n"
        "VALIDATION_RULES:\n"
        "  1. request.ticker must be uppercase, non-empty\n"
        "  2. request.start_date and end_date must be valid date objects\n"
        "  3. Each source must return at least 1 row or raise\n"
        "  4. Returned dates must fall within [start_date, end_date]\n"
        "  5. close column must be numeric (float)\n"
        "---\n"
        "DECISION_TREE:\n"
        "  FOR each source in ['bloomberg', 'reuters', 'yahoo']:\n"
        "    IF source == 'yahoo' and yahoo_mode == 'live':\n"
        "      -> Action: call yfinance.download(ticker, start, end)\n"
        "      -> IF yfinance fails (network, rate limit):\n"
        "         -> Action: fall back to stub data with warning\n"
        "    ELIF source == 'yahoo' and yahoo_mode == 'stub':\n"
        "      -> Action: generate synthetic data via MarketDataAgentStub\n"
        "    ELSE (bloomberg/reuters):\n"
        "      -> Action: call stub generator (placeholder for real connectors)\n"
        "    -> Action: attach metadata (row_count, date_range, fetch_timestamp)\n"
        "  -> Action: collect all results into list[DataSourceResult]\n"
        "---\n"
        "ERROR_HANDLING:\n"
        "  - Yahoo live failure: log warning, fall back to stub, continue\n"
        "  - Empty dataset from any source: exclude from results, log warning\n"
        "  - All sources fail: raise RuntimeError('No market data available from any source')\n"
        "---\n"
        "REACT_TEMPLATE:\n"
        "  Thought: retrieve comparable historical data from all configured sources.\n"
        "  Action: invoke market data tool.\n"
        "  Observation: source datasets returned with metadata."
    ),
    "data_quality_agent": (
        "ROLE: Data quality evaluator — computes readiness metrics per source.\n"
        "OBJECTIVE: Produce a ranked list of QualityMetric for source selection.\n"
        "---\n"
        "INPUT_CONTRACT:\n"
        "  - source_results: list[DataSourceResult]\n"
        "---\n"
        "OUTPUT_CONTRACT:\n"
        "  - metrics: list[QualityMetric] sorted by coverage_pct DESC\n"
        "  - Each metric has: source, rows, missing_close, duplicate_dates,\n"
        "    coverage_pct, start_date, end_date\n"
        "---\n"
        "VALIDATION_RULES:\n"
        "  1. Input list must not be empty\n"
        "  2. Each DataSourceResult must have non-empty data DataFrame\n"
        "  3. DataFrame must contain 'date' and 'close' columns\n"
        "  4. coverage_pct must be in [0.0, 100.0]\n"
        "---\n"
        "DECISION_TREE:\n"
        "  FOR each source_result in source_results:\n"
        "    -> Action: count total rows\n"
        "    -> Action: count missing 'close' values (isna().sum())\n"
        "    -> Action: count duplicate 'date' entries\n"
        "    -> Action: compute coverage_pct = (1 - missing_close / rows) * 100\n"
        "    -> Action: extract start_date, end_date from data\n"
        "    -> Action: build QualityMetric\n"
        "  -> Action: sort metrics by coverage_pct descending\n"
        "  -> Action: flag any source with coverage_pct < 50% as 'low quality'\n"
        "---\n"
        "ERROR_HANDLING:\n"
        "  - Empty source_results: raise ValueError('No source results to evaluate')\n"
        "  - Missing 'close' column: raise ValueError(f'Source {s} missing close column')\n"
        "  - All sources low quality: emit warning but continue with best available\n"
        "---\n"
        "REACT_TEMPLATE:\n"
        "  Thought: evaluate data readiness before source selection.\n"
        "  Action: compute quality metrics across sources.\n"
        "  Observation: ranked quality table produced."
    ),
    "source_selection_agent": (
        "ROLE: Source selector — chooses the best data source via human governance.\n"
        "OBJECTIVE: Capture a single selected source name for downstream processing.\n"
        "---\n"
        "INPUT_CONTRACT:\n"
        "  - quality_metrics: list[QualityMetric] (ranked by coverage_pct DESC)\n"
        "  - cli_source_override: str | None (from --source flag)\n"
        "  - non_interactive: bool\n"
        "---\n"
        "OUTPUT_CONTRACT:\n"
        "  - selected_source: str (one of 'bloomberg', 'reuters', 'yahoo')\n"
        "---\n"
        "VALIDATION_RULES:\n"
        "  1. quality_metrics must not be empty\n"
        "  2. selected_source must be one of the available sources\n"
        "  3. If cli_source_override is set, it must be a valid source name\n"
        "---\n"
        "DECISION_TREE:\n"
        "  IF cli_source_override is provided and valid:\n"
        "    -> Action: use cli_source_override, skip user prompt\n"
        "    -> Observation: 'CLI override: {source}'\n"
        "  ELIF non_interactive:\n"
        "    -> Action: auto-select top-ranked source from quality_metrics\n"
        "    -> Observation: 'Auto-selected: {source} (best coverage)'\n"
        "  ELSE:\n"
        "    -> Action: display quality table via rich\n"
        "    -> Action: prompt user to enter source name\n"
        "    -> IF invalid source entered:\n"
        "       -> Action: show error, re-display table, re-prompt\n"
        "    -> Observation: 'User selected: {source}'\n"
        "---\n"
        "ERROR_HANDLING:\n"
        "  - Empty quality_metrics: raise ValueError('No quality data for source selection')\n"
        "  - Invalid CLI override: raise ValueError(f'Unknown source: {override}')\n"
        "  - User cancels (EOF/KeyboardInterrupt): raise SystemExit(0)\n"
        "---\n"
        "REACT_TEMPLATE:\n"
        "  Thought: require human governance for source choice.\n"
        "  Action: prompt user with ranked options.\n"
        "  Observation: selected source captured."
    ),
    "gap_analysis_agent": (
        "ROLE: Gap analysis advisor — determines the best missing-data strategy.\n"
        "OBJECTIVE: Return a ranked list of GapFillSuggestion with rationales.\n"
        "---\n"
        "INPUT_CONTRACT:\n"
        "  - series: pd.Series (close prices with datetime index, may contain NaN)\n"
        "---\n"
        "OUTPUT_CONTRACT:\n"
        "  - suggestions: list[GapFillSuggestion] sorted by suitability DESC\n"
        "  - Each suggestion has: method (str), rationale (str)\n"
        "---\n"
        "VALIDATION_RULES:\n"
        "  1. series must not be empty\n"
        "  2. series must be numeric (float/int)\n"
        "  3. At least one suggestion must be returned\n"
        "---\n"
        "DECISION_TREE:\n"
        "  -> Action: compute gap statistics (total NaN count, max consecutive NaN,\n"
        "     gap_pct = NaN_count / total_rows * 100)\n"
        "  -> Action: compute volatility (std of non-NaN returns)\n"
        "  -> Action: compute trend strength (linear regression slope of non-NaN values)\n"
        "  -> Action: evaluate each method:\n"
        "     IF gap_pct < 5%:\n"
        "       -> 'linear': 'Low gap ratio ({gap_pct:.1f}%), linear interpolation is safe'\n"
        "     IF gap_pct >= 5% and gap_pct < 20%:\n"
        "       -> 'ffill_then_bfill': 'Moderate gaps ({gap_pct:.1f}%), forward-fill then back-fill'\n"
        "     IF gap_pct >= 20% or max_consecutive_nan > 10:\n"
        "       -> 'rolling_median': 'Large gaps ({gap_pct:.1f}%) or long runs of NaN, rolling median'\n"
        "     IF volatility > 0.03 (high vol):\n"
        "       -> 'rolling_median': 'High volatility ({vol:.4f}), rolling median smooths outliers'\n"
        "  -> Action: sort suggestions by suitability (primary: gap_pct fit, secondary: volatility fit)\n"
        "---\n"
        "ERROR_HANDLING:\n"
        "  - Empty series: raise ValueError('Cannot analyse gaps on empty series')\n"
        "  - All-NaN series: raise ValueError('Series is entirely NaN, cannot fill')\n"
        "  - Non-numeric series: raise TypeError('Series must be numeric')\n"
        "---\n"
        "REACT_TEMPLATE:\n"
        "  Thought: determine missing-data strategy suitability.\n"
        "  Action: run gap analysis on chosen source.\n"
        "  Observation: method recommendations available."
    ),
    "timeseries_generation_agent": (
        "ROLE: Time-series constructor — builds a continuous, gap-free series.\n"
        "OBJECTIVE: Produce a DataFrame with complete date range and no NaN close values.\n"
        "---\n"
        "INPUT_CONTRACT:\n"
        "  - source_df: pd.DataFrame (columns: date, ticker, close, source)\n"
        "  - method: str ('linear' | 'ffill_then_bfill' | 'rolling_median')\n"
        "---\n"
        "OUTPUT_CONTRACT:\n"
        "  - continuous_df: pd.DataFrame with columns: date, ticker, close, source,\n"
        "    filled (bool — True where value was imputed)\n"
        "  - All dates from min(date) to max(date) present (business-day frequency)\n"
        "  - No NaN values in 'close' column\n"
        "---\n"
        "VALIDATION_RULES:\n"
        "  1. source_df must contain 'date' and 'close' columns\n"
        "  2. method must be one of the three supported values\n"
        "  3. Output must have no NaN in 'close'\n"
        "  4. Output date range must match input date range\n"
        "  5. Output must have a 'filled' boolean column\n"
        "---\n"
        "DECISION_TREE:\n"
        "  -> Action: deduplicate by date (keep last occurrence)\n"
        "  -> Action: set 'date' as index, sort ascending\n"
        "  -> Action: reindex to full business-day range [min_date, max_date]\n"
        "  -> Action: mark original vs. inserted rows in 'filled' column\n"
        "  -> Action: apply selected fill method:\n"
        "     IF method == 'linear':\n"
        "       -> interpolate(method='linear') on 'close'\n"
        "     ELIF method == 'ffill_then_bfill':\n"
        "       -> fillna(method='ffill').fillna(method='bfill')\n"
        "     ELIF method == 'rolling_median':\n"
        "       -> fillna with rolling(window=5, min_periods=1).median()\n"
        "       -> fill any remaining NaN with bfill/ffill\n"
        "  -> Action: reset index, ensure 'date' is a column\n"
        "  -> Action: verify no NaN remains in 'close'\n"
        "---\n"
        "ERROR_HANDLING:\n"
        "  - Missing columns: raise ValueError('source_df missing required columns')\n"
        "  - Unknown method: raise ValueError(f'Unknown gap method: {method}')\n"
        "  - NaN remains after fill: raise RuntimeError('Gap fill incomplete, NaN remains')\n"
        "  - Empty DataFrame after dedup: raise ValueError('No data after deduplication')\n"
        "---\n"
        "REACT_TEMPLATE:\n"
        "  Thought: construct continuous time series for downstream usage.\n"
        "  Action: apply selected fill method on deduplicated data.\n"
        "  Observation: continuous series generated."
    ),
    "reporting_agent": (
        "ROLE: Audit and reporting — persists artifacts and prints run summary.\n"
        "OBJECTIVE: Export all run artifacts (CSV, JSON) and print a human-readable trace.\n"
        "---\n"
        "INPUT_CONTRACT:\n"
        "  - framework: str ('autogen' | 'langchain')\n"
        "  - request: PipelineRequest\n"
        "  - selected_source: str\n"
        "  - gap_method: str\n"
        "  - quality: list[QualityMetric]\n"
        "  - continuous: pd.DataFrame\n"
        "  - events: list[ReActEvent]\n"
        "  - artifact_manager: AuditArtifactManager\n"
        "---\n"
        "OUTPUT_CONTRACT:\n"
        "  - artifact_paths: dict[str, str] with keys:\n"
        "    'quality_csv', 'continuous_series_csv', 'run_report_json'\n"
        "  - Console output: quality table, series summary, ReACT trace, artifact paths\n"
        "---\n"
        "VALIDATION_RULES:\n"
        "  1. All input artifacts must be non-None\n"
        "  2. Export directory must be writable\n"
        "  3. ReACT trace must contain at least one event\n"
        "---\n"
        "DECISION_TREE:\n"
        "  -> Action: export quality metrics to CSV via artifact_manager\n"
        "  -> Action: export continuous series to CSV via artifact_manager\n"
        "  -> Action: build run report dict (request, decisions, quality, trace, paths)\n"
        "  -> Action: export run report to JSON via artifact_manager\n"
        "  -> Action: print quality summary table via CLIReporter\n"
        "  -> Action: print generated series summary (row count, date range, method)\n"
        "  -> Action: print full ReACT trace (agent, thought, action, observation per step)\n"
        "  -> Action: print artifact file paths\n"
        "---\n"
        "ERROR_HANDLING:\n"
        "  - Export directory unwritable: fall back to tempdir, log warning\n"
        "  - Empty ReACT trace: print warning but still export data artifacts\n"
        "  - CSV/JSON write failure: print error but continue with remaining exports\n"
        "---\n"
        "REACT_TEMPLATE:\n"
        "  Thought: provide auditable decision and output summary.\n"
        "  Action: export artifacts and print run summary.\n"
        "  Observation: run report and files persisted."
    ),
}